### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by m-anshuman2166** [canewsin/python_ide#3]
Hi, I liked your app, and took some of help (Native libs) from your project.

Could you help me?
Could you list out native functions present in libpython.so?

[`I dont know dart, I'm programming in java']

**Comment by canewsin** [comment]
@m-anshuman2166 
https://github.com/GRRedWings/python3-android
those are built from python3 project, visit above link for ref.

**Comment by m-anshuman2166** [comment]
cool

**Comment by m-anshuman2166** [comment]
@canewsin just a bit offtopic here but could you help me run python code in java ?
